config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    
    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/signup", to: "users#new"
    post "signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get ":id/followings", to: "followings#index", as: "followings"
    get ":id/followers", to: "followers#index", as: "followers"
    resources :relationships, only: %i(create destroy)
    resources :users, except: :new
    resources :account_activations, only: :edit
    resources :password_resets, except: %i(index show destroy)
    resources :microposts
  end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= paginate @feed_items, theme: "twitter-bootstrap-3" %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for @micropost do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: t("micropost.placeholder") %>
  </div>
  <%= f.submit t("micropost.post"), class: "btn btn-primary" %>
  <span class="image">
    <%= f.file_field :image, accept: Settings.micropost.image_accept %>
  </span>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <%= link_to followings_path @user do %>
    <strong id="following" class="stat">
      <%= @user.following.size %>
    </strong>
    <%= t "follow.following" %>
  <% end %>
 <%= link_to followers_path @user do %>
    <strong id="followers" class="stat">
      <%= @user.followers.size %>
    </strong>
    <%= t "follow.followers" %>
   <% end %>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: Settings.micropost.size_post), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to t("micropost.view_profile"), current_user %></span>
<span><%= pluralize current_user.microposts.size, t("micropost.title") %></span>